### ISSUE TITLE
Can't install pyicu in my mac. Error: library not found for -licule

### ISSUE THREAD

**Issue by miguelwon** [ovalhub/pyicu#34]
Hi,
So I'm having some troubles installing pyicu in my mac. I'm running the following command:

CFLAGS='-I/usr/local/opt/icu4c/include -I/opt/local/include' LDFLAGS=-L/usr/local/opt/icu4c/lib pip install pyicu

and it results in the error:

ld: library not found for -licule

Which library is this licule?

**Comment by ovalhub** [comment]
It appears that ICU 58 dropped the layout engine support (icu le). PyICU has not yet been upgraded to icu 58, please use icu 57.x until it is.

Andi..

**Comment by miguelwon** [comment]
Ok, it's working now. 
Thanks!

**Comment by ovalhub** [comment]
this is now fixed in version 1.9.4, ICU 58.1 is supported

**Comment by sassanh** [comment]
Am I missing something:
```
> pip install --no-cache-dir pyicu

...
    clang++ -bundle -undefined dynamic_lookup build/temp.macosx-10.11-x86_64-3.5/_icu.o build/temp.macosx-10.11-x86_64-3.5/bases.o build/temp.macosx-10.11-x86_64-3.5/calendar.o build/temp.macosx-10.11-x86_64-3.5/char.o build/temp.macosx-10.11-x86_64-3.5/charset.o build/temp.macosx-10.11-x86_64-3.5/collator.o build/temp.macosx-10.11-x86_64-3.5/common.o build/temp.macosx-10.11-x86_64-3.5/dateformat.o build/temp.macosx-10.11-x86_64-3.5/errors.o build/temp.macosx-10.11-x86_64-3.5/format.o build/temp.macosx-10.11-x86_64-3.5/idna.o build/temp.macosx-10.11-x86_64-3.5/iterators.o build/temp.macosx-10.11-x86_64-3.5/layoutengine.o build/temp.macosx-10.11-x86_64-3.5/locale.o build/temp.macosx-10.11-x86_64-3.5/normalizer.o build/temp.macosx-10.11-x86_64-3.5/numberformat.o build/temp.macosx-10.11-x86_64-3.5/regex.o build/temp.macosx-10.11-x86_64-3.5/script.o build/temp.macosx-10.11-x86_64-3.5/search.o build/temp.macosx-10.11-x86_64-3.5/shape.o build/temp.macosx-10.11-x86_64-3.5/spoof.o build/temp.macosx-10.11-x86_64-3.5/transliterator.o build/temp.macosx-10.11-x86_64-3.5/tzinfo.o build/temp.macosx-10.11-x86_64-3.5/unicodeset.o -licui18n -licuuc -licudata -licule -o build/lib.macosx-10.11-x86_64-3.5/_icu.cpython-35m-darwin.so -L/usr/local/lib
    ld: library not found for -licule
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    error: command 'clang++' failed with exit status 1

    ----------------------------------------
Command "/Users/sassanharadji/.virtualenvs/mhelli/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/private/var/folders/sx/995cq4316_57jgdyhwjvf9rw0000gn/T/pip-build-azzzr7it/pyicu/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/sx/995cq4316_57jgdyhwjvf9rw0000gn/T/pip-vrnl4ui3-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/sassanharadji/.virtualenvs/mhelli/bin/../include/site/python3.5/pyicu" failed with error code 1 in /private/var/folders/sx/995cq4316_57jgdyhwjvf9rw0000gn/T/pip-build-azzzr7it/pyicu/
```

**Comment by sassanh** [comment]
@ovalhub checking https://github.com/ovalhub/pyicu/commit/a7075b2f3a2a2688aa70faa745401aaa6378f481 seems like you forgot to update `setup.py`.

**Comment by sassanh** [comment]
I'm using https://github.com/sassanh/pyicu/commit/9d4c5bc551f54388c7cb02d2b591d5b4f251d701 which is just a temporary fix. Will update as soon as you provide an official release.

**Comment by ovalhub** [comment]
> On Nov 7, 2016, at 09:13, Sassan Haradji <notifications@github.com> wrote:
> 
> Am I missing something:
> 
Yes, you are using ICU 58 with PyICU 1.9.3.
The latest icu dropped support for layout engine.
Please, upgrade to PyICU 1.9.4.

Andi..

**Comment by sassanh** [comment]
@ovalhub no I'm using PyICU 1.9.4, you fixed everything in PyICU 1.9.4 except `setup.py`. It still needs libicule.

**Comment by ovalhub** [comment]
Ah yes, you're right. I still have the old icule lib laying around so didn't notice. I should have a fix shortly.
Sorry for the mess up.

Andi..

**Comment by sassanh** [comment]
Thanks 👍

**Comment by ovalhub** [comment]
On Mon, 7 Nov 2016, Sassan Haradji wrote:

> Thanks ?

I just added an ICU version check into setup.py that excludes icule from the 
libraries list if the version of ICU used is >= 58.

Can you please check that this works on your platform and let me know.
If it works, I'll release 1.9.5 shortly.

Thanks !

Andi..

**Comment by sassanh** [comment]
Sure

**Comment by sassanh** [comment]
```
Collecting git+git://github.com/ovalhub/pyicu.git
  Cloning git://github.com/ovalhub/pyicu.git to /private/var/folders/sx/995cq4316_57jgdyhwjvf9rw0000gn/T/pip-787furgd-build
  Running command git clone -q git://github.com/ovalhub/pyicu.git /private/var/folders/sx/995cq4316_57jgdyhwjvf9rw0000gn/T/pip-787furgd-build
  Running setup.py (path:/private/var/folders/sx/995cq4316_57jgdyhwjvf9rw0000gn/T/pip-787furgd-build/setup.py) egg_info for package from git+git://github.com/ovalhub/pyicu.git
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/sx/995cq4316_57jgdyhwjvf9rw0000gn/T/pip-787furgd-build/setup.py", line 83, in <module>
        elif ICU_VERSION < '58':
    TypeError: unorderable types: bytes() < str()
```

I guess we should check `str(ICU_VERSION)` I'm using python 3.

**Comment by ovalhub** [comment]
On Mon, 7 Nov 2016, Sassan Haradji wrote:

> ```
> Collecting git+git://github.com/ovalhub/pyicu.git
>  Cloning git://github.com/ovalhub/pyicu.git to /private/var/folders/sx/995cq4316_57jgdyhwjvf9rw0000gn/T/pip-787furgd-build
>  Running command git clone -q git://github.com/ovalhub/pyicu.git /private/var/folders/sx/995cq4316_57jgdyhwjvf9rw0000gn/T/pip-787furgd-build
>  Running setup.py (path:/private/var/folders/sx/995cq4316_57jgdyhwjvf9rw0000gn/T/pip-787furgd-build/setup.py) egg_info for package from git+git://github.com/ovalhub/pyicu.git
>    Running command python setup.py egg_info
>    Traceback (most recent call last):
>      File "<string>", line 1, in <module>
>      File "/private/var/folders/sx/995cq4316_57jgdyhwjvf9rw0000gn/T/pip-787furgd-build/setup.py", line 83, in <module>
>        elif ICU_VERSION < '58':
>    TypeError: unorderable types: bytes() < str()
> ```
>
> I guess we should check `str(ICU_VERSION)` I'm using python 3.

Good catch. Added conditional since str(b'58') helpfully produces "b'58'"
and I had to str(ICU_VERSION, 'ascii') to get unicode '58'.

Please, try it again and let me know.
Thanks !

Andi..

**Comment by sassanh** [comment]
@ovalhub It's working on my machine 👍

**Comment by ovalhub** [comment]
On Mon, 7 Nov 2016, Sassan Haradji wrote:

> @ovalhub It's working on my machine ?

Great. Thank you for checking.

Andi..
